apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Staging environment project
  sourceRepos:
    - https://github.com/anandbte6113/gitops-platform.git
    - https://charts.helm.sh/stable
  destinations:
    - server: https://172.19.0.4:6443
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
