---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-gateway-secret
  namespace: api-gateway
spec:
  encryptedData:
    api-key: AgBmPLKDQz2aplgsWzCusokZo9Zf62kxUAyMaNWP8f4K0xAiaxwJuCp+wF0x8Yts5coDny3VbU1LTnTyjlc3CJxXUdeP6ideB9nyxVKwpSsmoVCrkjNVFAoF/w8kxOmHnVGLSf+ceeHlk3rfYY8yiv1iEh1wxuItzv1+IpyKJGHorGBOOvkwt3MhAbgHucO+X7x/DOM4mmnJ4Ind7zxHtQqSYlN2+Yw/jRYssl4gyTrG2MbI3L6sQ8NiNHGiGRwco3z7oSbfnOdWWafjHw2rBNqMDXO1CxuWDTy7ACPW1ICaQ5PaPrD0Qbpasnkzt/0pBTGLw3reaPscOTrlgbu+13KD42wZHAvqeQsN/LMmXigxVdbqs4xX+W3D7kpr/OWCJbFhU6G49cpWRB7UrPL9TRknDEBocaa3t5phNe+3ecRSdgoWg7boxMIuA9tBkLKognDpC3zr0+HXxbA8N38ESwUOWv7d5rh0pmqg25Clf9xklsklaSOPvviWMquusH83epinFQd1vZKp4AaYccdbuu99O/SpbjD2AeypXe1WT0xUJCm/atU8yUPIoHqlO3yYAtCzt2UFoQrrzRVFMPMp6OiwKmmgRJtcClUhi2iamOEwj/8kyyoXSRTitP32B7O+nxbyjdhxGe+ac+U2L5LZNpGwhlL6qp57gzXd1UCL/OlingAdXhEVVJ+C3lAyyp7W7XyPeOZR09IsA9M2/TKpH06ZAcOSoVcW
  template:
    metadata:
      creationTimestamp: null
      name: api-gateway-secret
      namespace: api-gateway
    type: Opaque
