apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: dev
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.18
    helm:
      releaseName: external-secrets
  destination:
    server: https://172.19.0.3:6443
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
