apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: dev
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.15.3
    helm:
      releaseName: sealed-secrets
      values: |
        fullnameOverride: sealed-secrets-controller
  destination:
    server: https://172.19.0.3:6443
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
