apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: dev
  source:
    repoURL: https://github.com/anandbte6113/gitops-platform.git
    targetRevision: HEAD
    path: vendor/sealed-secrets
  destination:
    server: https://172.19.0.3:6443
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
