apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Wave 1 — controllers (install CRDs first)
  - controllers/sealed-secrets.yaml
  - controllers/sealed-secrets-dev.yaml
  - controllers/sealed-secrets-staging.yaml
  - controllers/eso.yaml
  - controllers/eso-dev.yaml
  - controllers/eso-staging.yaml
  # Wave 2 — projects, RBAC, applicationsets
  - projects/dev-project.yaml
  - projects/staging-project.yaml
  - rbac/argocd-rbac-cm.yaml
  - applicationsets/microservices-appset.yaml
  # Wave 3 — secret stores (after ESO CRDs exist)
  - secret-stores/cluster-secret-store.yaml
  - cluster-config/dev-config.yaml
  - cluster-config/staging-config.yaml
