apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-service-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: localstack-secret-store
    kind: ClusterSecretStore
  target:
    name: order-service-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: order-service/db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: order-service/db-credentials
        property: password
