apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - git:
        repoURL: https://github.com/anandbte6113/gitops-platform.git
        revision: HEAD
        directories:
          - path: services/*
  template:
    metadata:
      name: '{{path.basename}}-dev'
    spec:
      project: dev
      source:
        repoURL: https://github.com/anandbte6113/gitops-platform.git
        targetRevision: HEAD
        path: 'services/{{path.basename}}/overlays/dev'
      destination:
        server: https://172.19.0.3:6443
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - git:
        repoURL: https://github.com/anandbte6113/gitops-platform.git
        revision: HEAD
        directories:
          - path: services/*
  template:
    metadata:
      name: '{{path.basename}}-staging'
    spec:
      project: staging
      source:
        repoURL: https://github.com/anandbte6113/gitops-platform.git
        targetRevision: HEAD
        path: 'services/{{path.basename}}/overlays/staging'
      destination:
        server: https://172.19.0.4:6443
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
