---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-gateway-secret
  namespace: api-gateway
spec:
  encryptedData:
    api-key: AgCw5vCW9488Azr5ttZlwts791kREjFaSpX5cP3SmU5Pa2eb3KvSMplySCB+iRJ0TSLKH+KDNNjCCn0xe4aWIbhN1Ay+9kiKvHP7GNi7Rs9RwLX4O/URS30qHvWMuc9mmz6jSUHbpDIA/sV4vyqeWVqHkTNQfQ47CWCvsbtCctMC4wQstD0SRWaW/viTBQ0mTLPFYjar98hbZrSkTPBOt0mXZVxRqKOV1kZyTO4scAuAXV2fcQjDcCH9Xx7ulnfaQeeB0yiPocn+czijrXcHCFtbKRBanpPfoJXPNJMp52bse3AYkoFyMrUrej0WyCSdAe8IBPB6DZHV5zEPaWZaUVz02/2cT2tezwIUylLfI2glrXOjYyDW5/KZ089ugaCuR8zRByCiA3tUa6UXN5OHrgjseTkbN2oxqwfidFfQUXz8qkOU/EW7griqZi2ncCJUIn8zRzxfLBrHzmDKjUXq1h/+eDJiuIATxXSPN567ns5fwgg1UKHC+O+VQNaXFZmhfb0xwR0TXjhmc8xT3u734YCMs0ouF7pJX7AttXyeEaYBa7yyNB2IsWL0aFA2i33xhJf066jYWCu4x5wHCQzP3LfWnuDPqE5GwMh3awDFE7r19iEypda5NTDsVPg8O/Gc2DLcmMZ5TISRNmXb4jywlBLb4ab7YRYmWf7ZOsn2rHrogtEVlnoOgE4KxzFefXbYmANd5NpRh/OYceV7d071iyousMY=
  template:
    metadata:
      creationTimestamp: null
      name: api-gateway-secret
      namespace: api-gateway
    type: Opaque
